sudo: required
dist: trusty
os: linux
language: minimal
cache:
  directories:
  - depends/built
  - depends/sdk-sources
  - "$HOME/.ccache"
git:
  depth: false
env:
  global:
  - MAKEJOBS=-j3
  - RUN_TESTS=false
  - CHECK_DOC=0
  - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
  - CCACHE_SIZE=100M
  - CCACHE_TEMPDIR=/tmp/.ccache-temp
  - CCACHE_COMPRESS=1
  - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
  - SDK_URL=https://bitcoincore.org/depends-sources/sdks
  - WINEDEBUG=fixme-all
  - RKCOIN_SCRYPT=0
  matrix:
  - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf python3-pip zip" DEP_OPTS="NO_QT=1"
    CHECK_DOC=0 GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
  - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PACKAGES="python3
    python3-dev python3-pip nsis g++-mingw-w64-i686 wine1.6 zip" RUN_TESTS=false GOAL="install"
    BITCOIN_CONFIG="--enable-reduce-exports" RKCOIN_SCRYPT=1
  - HOST=x86_64-unknown-linux-gnu PACKAGES="python3-zmq python3-dev python3-pip qt4-dev-tools
    libssl-dev libevent-dev bsdmainutils libboost-system-dev libboost-filesystem-dev
    libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev
    libdb5.1++-dev libminiupnpc-dev libzmq3-dev libprotobuf-dev protobuf-compiler
    libqrencode-dev xvfb zip" NO_DEPENDS=1 NEED_XVFB=1 RUN_TESTS=false GOAL="install"
    BITCOIN_CONFIG="--enable-zmq --with-incompatible-bdb --enable-glibc-back-compat
    --enable-reduce-exports --with-gui=qt4 CPPFLAGS=-DDEBUG_LOCKORDER" RKCOIN_SCRYPT=1
  - HOST=i686-pc-linux-gnu PACKAGES="g++-multilib python3-zmq python3-dev python3-pip
    zip" DEP_OPTS="NO_QT=1" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-zmq
    --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++"
    USE_SHELL="/bin/dash" RKCOIN_SCRYPT=1
  - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PACKAGES="python3
    python3-dev python3-pip nsis g++-mingw-w64-x86-64 wine1.6 zip" RUN_TESTS=false
    GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports --enable-sse2" RKCOIN_SCRYPT=1
  - HOST=x86_64-unknown-linux-gnu PACKAGES="python3-zmq python3-dev python3-pip qtbase5-dev
    qttools5-dev-tools protobuf-compiler libdbus-1-dev libharfbuzz-dev zip" DEP_OPTS="NO_QT=1
    NO_UPNP=1 DEBUG=1 ALLOW_HOST_PACKAGES=1" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-zmq
    --with-gui=qt5 --enable-glibc-back-compat --enable-reduce-exports --enable-sse2
    CPPFLAGS=-DDEBUG_LOCKORDER" RKCOIN_SCRYPT=1
  - HOST=x86_64-unknown-linux-gnu PACKAGES="python3 python3-dev python3-pip zip" DEP_OPTS="NO_WALLET=1"
    RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports
    --enable-sse2" RKCOIN_SCRYPT=1
  - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin
    libz-dev libbz2-dev libtiff-tools python-dev zip" BITCOIN_CONFIG="--enable-gui
    --enable-reduce-exports --enable-werror --enable-sse2" OSX_SDK=10.11 GOAL="deploy"
before_install:
- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
  sed "s|::|:|g")
install:
- if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ;
  fi
- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
  --no-upgrade -qq $PACKAGES; fi
- if [ "$CHECK_DOC" = 1 -a "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then travis_retry
  pip3 install flake8 --user; fi
- if [ "$RKCOIN_SCRYPT" = 1 ]; then travis_retry sudo pip3 install litecoin_scrypt
  --allow-external litecoin_scrypt; fi
before_script:
- if [ "$CHECK_DOC" = 1 -a "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then contrib/devtools/commit-script-check.sh
  $TRAVIS_COMMIT_RANGE; fi
- if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/git-subtree-check.sh src/crypto/ctaes;
  fi
- if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/git-subtree-check.sh src/secp256k1;
  fi
- if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/git-subtree-check.sh src/univalue;
  fi
- if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/git-subtree-check.sh src/leveldb;
  fi
- if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/check-doc.py; fi
- if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/check-rpc-mappings.py .; fi
- if [ "$CHECK_DOC" = 1 -a "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then contrib/devtools/lint-all.sh;
  fi
- unset CC; unset CXX
- mkdir -p depends/SDKs depends/sdk-sources
- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
  curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz;
  fi
- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
- if [ -z "$NO_DEPENDS" ]; then make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS; fi
- if [ "$NEED_XVFB" = 1 ]; then export DISPLAY=:99.0; /sbin/start-stop-daemon --start
  --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb
  -- :99 -ac; fi
script:
- if [ "$CHECK_DOC" = 1 -a "$TRAVIS_REPO_SLUG" = "radimkohout/rkcoin" -a "$TRAVIS_PULL_REQUEST"
  = "false" ]; then while read LINE; do travis_retry gpg --keyserver hkp://subset.pool.sks-keyservers.net
  --recv-keys $LINE; done < contrib/verify-commits/trusted-keys; fi
- if [ "$CHECK_DOC" = 1 -a "$TRAVIS_REPO_SLUG" = "radimkohout/rkcoin" -a "$TRAVIS_PULL_REQUEST"
  = "false" ]; then contrib/verify-commits/verify-commits.sh; fi
- export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
- if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
- OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
- BITCOIN_CONFIG_ALL="--disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST
  --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
- if [ -z "$NO_DEPENDS" ]; then depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE;
  fi
- test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
- mkdir build && cd build
- 
- "../configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || (
  cat config.log && false)"
- make distdir VERSION=$HOST
- cd rkcoin-$HOST
- "./configure --cache-file=../config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG ||
  ( cat config.log && false)"
- make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL
  V=1 ; false )
- export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
- if [ "$RUN_TESTS" = "true" ]; then travis_wait 30 make $MAKEJOBS check VERBOSE=1;
  fi
- if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then extended="--extended --exclude feature_pruning,feature_dbcrash";
  fi
- if [ "$RUN_TESTS" = "true" ]; then test/functional/test_runner.py --combinedlogslen=4000
  --coverage --quiet ${extended}; fi
- zip -r zip-$HOST.zip $TRAVIS_BUILD_DIR
after_script:
- echo $TRAVIS_COMMIT_RANGE
- echo $TRAVIS_COMMIT_LOG
deploy:
  provider: releases
  file: zip-$HOST.zip
  on:
    repo: radimkohout/rkcoin
  username: radimkohout
  password:
    secure: E44vAulBPuGKBzSusK5PtQFVnx/fxzBU+Y7i8q9QvUsfb1GYHz/OS8kDTpQcQTl6gtwXdLRXtQaqiDP2TjKu+YFVE8LaYdCGfcVdo+q8PTve2QsM9oe5qwF7LcEQHINrB7qER97JhLIhmMYJituf2Fdf1d3BoSjPErOUdzXkE4G4uSGyXoRCDrtHqlrA8s56FkwZbD7CC4G8cLwVPx9XTnxd4cVZrOEmRwmaLF9hc4KBjW3b8AGs5YOgp69QAuGjp309szmKwWxkbnV1LbwG+55qCZThHsPJ5r6Zh37un8Eb58kgz4e1GoA6Hha7aHFF1MFMM69xb5XXkY8V/nPK4B4V33+LeNSXxwloOHgWfJacqhW0Sx9Lagcd5Tp6JRkqSAmsE6NcG6e6MgJT/GMYdhWvxfArcGYhPVF0Z1YtQtFTrxLjlAqI5CrWXF92oNrxDQ4mZMdaabDBhfB89ESZqMPfBBDlfUfYMQOhtNr3Z1suWaEvJ/SEZdGtXTA+e/itAssUIxMY8NVcgj5WlTIQwu4XZbOxSNPA2ajHCk8t+oXeKHiMxoAIea1Ozhxjn8baX8J5PaY9qq/5yVCPz4TxbooG/p+7bEdQotghGJtuRSjRVel/IuZl2J3CqmqB0Bc17sMpw9yJa/3r4SX7a4DkjXTrFUmHDCSrJ38iriNcJKo=
  skip_cleanup: true
api_key:
  secure: dvbrVZ4qz8Zvf+n1Ws0yYFrEhtOgfQRWpOzSOmEKjnp/JCxqi+Qu4NjOaOoTXnTDV38Ck5dnrghKEL/DBVMlLsAFCpj0thYRv59kXB9PqSXXQIs8n4W/96kLG+Ff7q2rsJ8GWbi/MClxF9wuJqY40a3bYg8fMx3fEAiWXObf91CIVY8HVFlArb9nUGzyloHE7m8Um4bcu78qUEBWu+ZFKkFbbNPs15cIi6pS0jnoiRffh2TNrRghG9Zz9aTKgbtY+fobhQTD+JhmKaWupjgOkY1pOAVJhQsgFsX8aLlGs8I3bQU528T0lbLZlSNudFqYy2cYkO3czjQ8w5R6Yx+3gISBFiie7mXAraPWM8IFf1lWlLnmgjrR6aVu5B6hPsgjLkXMaxpy0pXXyog+AUocKB5jEdOj/xHbjkXVIgvdUQRfkFZ8kALgo7OHbzbkxQ1iFNGlY+dEwB/ILtnhdmuLSg4hL2Mh7nwQP0KWRiQL3uKRCL3cM3JU0eSxungHV4bukQuQANKDd3E/rQr5KfMEzzsuKkbQCW3q3gFIUUedk+Xk8ZLWkRnQrEryN96JucWrWPPJRZ8T3huV5JP2fjgaN4R43BpWhYySHaXaOZxYueAXDiT6l3vg8Vopz1BfjVSFPjxIPIU+6wMhH3LxX6+d6jUNkR090dAwu+Sg9hdXA6o=
